---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: restart httpd
  service: name=httpd state=restarted enabled=yes
