---
- name: コンポーザーがインストールされているかを確認
  stat: path=/usr/local/bin/composer
  register: composer_bin
  tags: composer

- block:
  - name: ダウンロード
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer

  - name: インストール
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin

  - name: 名前を変更して/usr/local/binへ
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer

  - name: ファイル権限の変更
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file

  when: not composer_bin.stat.exists
  tags: composer
