---
# 共通設定
- hosts: all
  become: true
  user: vagrant
  roles:
    - common

# webサーバー設定
- hosts: web
  become: true
  user: vagrant
  roles:
    - nginx
    - php7
    - composer
    - phalcon3

# dbサーバー設定
- hosts: db
  become: true
  user: vagrant
  roles:
    - mysql

# redisサーバー設定
- hosts: redis
  become: true
  user: vagrant
  roles:
    - redis

# memcachedサーバー設定
- hosts: memcache
  become: true
  user: vagrant
  roles:
    - memcached

# 管理サーバー設定
- hosts: server_manager
  become: true
  user: vagrant
  roles:
    - mysql-cli
    - redis
    - jenkins


