---
# 共通設定
- hosts: all
  become: true
  user: vagrant
  roles:
    - common
      #- memcached
      #- composer
      #- redis
      #- apache
      #- mysql

# webサーバー設定
- hosts: web
  become: true
  user: vagrant
  roles:
    - nginx
    - php7
    - composer
    - phalcon3
